"""Catálogo de sources/sinks por linguagem, dos modelos do CodeQL (GERADO).

NÃO EDITE À MÃO — gerado por `scripts/import_codeql_models.py`.

Semeado a partir dos arquivos `*.model.yml` ("Models as Data") de
github.com/github/codeql, sob licença **MIT**, Copyright (c) 2006-2025
GitHub, Inc. Deles extraímos apenas NOMES DE API e a categoria da regra —
não as queries, não as bibliotecas QL, e nada do motor/CLI do CodeQL, que é
proprietário e não foi usado.

O que fica de fora, e por quê: `log-injection` (a maior categoria deles) e as
famílias `credentials-*`/`encryption-*` cobrem defeitos que este motor não
reporta; importá-las só encheria o relatório. Fontes só de categoria `remote`.

Como o motor casa chamadas pelo ÚLTIMO SEGMENTO do nome, nomes genéricos
(`write`, `query`, `open`) são descartados na importação: sem tipo nem pacote
eles disparariam em qualquer código.

O usuário continua podendo ajustar tudo em `.codegraph/taint.json`.
"""

from __future__ import annotations


CATALOG_CODEQL: dict[str, dict[str, frozenset[str]]] = {
    "csharp": {
        "sources": frozenset({
            "EndReceive", "GetStream", "Receive", "ReceiveAsync",
            "get_BaseUri", "get_Body", "get_Cookies", "get_Headers",
            "get_PathParameters", "get_RawPath", "get_RawQueryString", "get_Uri",
        }),
        "sinks": frozenset({
            "BinaryWrite", "Column<T>", "ColumnAsync<T>", "ColumnDistinct<T>",
            "ColumnDistinctAsync<T>", "ColumnLazy<T>", "CreateSQLQuery", "Custom",
            "CustomAsync", "Dictionary<K,V>", "DictionaryAsync<K,V>", "EntityCommand",
            "ExecCachedLua", "ExecCachedLuaAsync", "ExecLua", "ExecLuaAsInt",
            "ExecLuaAsIntAsync", "ExecLuaAsList", "ExecLuaAsListAsync", "ExecLuaAsString",
            "ExecLuaAsStringAsync", "ExecLuaAsync", "Execute", "ExecuteAsync",
            "ExecuteDataRow", "ExecuteDataRowAsync", "ExecuteDataset", "ExecuteDatasetAsync",
            "ExecuteNonQuery", "ExecuteNonQueryAsync", "ExecuteReader", "ExecuteReaderAsync",
            "ExecuteScalar", "ExecuteScalar<T>", "ExecuteScalarAsync", "ExecuteScalarAsync<T>",
            "ExecuteSql", "ExecuteSqlAsync", "ExecuteSqlCommand", "ExecuteSqlCommandAsync",
            "ExecuteSqlRaw", "ExecuteSqlRawAsync", "ExecuteXmlReader", "Exists<T>",
            "ExistsAsync<T>", "FromSqlRaw<TEntity>", "KeyValuePairs", "KeyValuePairsAsync<K,V>",
            "LoadLuaScript", "LoadLuaScriptAsync", "Lookup<K,V>", "LookupAsync<K,V>",
            "MarkupString", "OdbcCommand", "OleDbCommand", "Query<T>",
            "Query<TFirst,TSecond,TReturn>", "Query<TFirst,TSecond,TThird,TFourth,TFifth,TReturn>", "Query<TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TReturn>", "Query<TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn>",
            "Query<TFirst,TSecond,TThird,TFourth,TReturn>", "Query<TFirst,TSecond,TThird,TReturn>", "Query<TReturn>", "QueryAsync",
            "QueryAsync<T>", "QueryAsync<TFirst,TSecond,TReturn>", "QueryAsync<TFirst,TSecond,TThird,TFourth,TFifth,TReturn>", "QueryAsync<TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TReturn>",
            "QueryAsync<TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn>", "QueryAsync<TFirst,TSecond,TThird,TFourth,TReturn>", "QueryAsync<TFirst,TSecond,TThird,TReturn>", "QueryAsync<TReturn>",
            "QueryFirst", "QueryFirst<T>", "QueryFirstAsync", "QueryFirstAsync<T>",
            "QueryFirstOrDefault", "QueryFirstOrDefault<T>", "QueryFirstOrDefaultAsync", "QueryFirstOrDefaultAsync<T>",
            "QueryMultiple", "QueryMultipleAsync", "QuerySingle", "QuerySingle<T>",
            "QuerySingleAsync", "QuerySingleAsync<T>", "QuerySingleOrDefault", "QuerySingleOrDefault<T>",
            "QuerySingleOrDefaultAsync", "QuerySingleOrDefaultAsync<T>", "RowCount", "RowCountAsync",
            "SQLiteCommand", "SQLiteDataAdapter", "Scalar<T>", "ScalarAsync<T>",
            "Select<T>", "Select<TModel>", "SelectAsync<T>", "SelectAsync<TModel>",
            "SelectLazy<T>", "SelectNonDefaults<T>", "SelectNonDefaultsAsync<T>", "Single<T>",
            "SingleAsync<T>", "SqlColumn<T>", "SqlColumnAsync<T>", "SqlCommand",
            "SqlDataAdapter", "SqlList<T>", "SqlListAsync<T>", "SqlQuery",
            "SqlQuery<TElement>", "SqlScalar<T>", "SqlScalarAsync<T>", "TransmitFile",
            "UnsafeAnd", "UnsafeFrom", "UnsafeGroupBy", "UnsafeHaving",
            "UnsafeOr", "UnsafeOrderBy", "UnsafeSelect", "UnsafeWhere",
            "UpdateDataset", "UpdateDatasetAsync", "WriteFile", "op_Explicit",
        }),
    },
    "go": {
        "sources": frozenset({
            "AcceptLanguages", "Accepted", "AllParams", "BindHeader",
            "BindJSON", "BindQuery", "BindUri", "BindWith",
            "BindXML", "BindYAML", "BodyGunzip", "BodyInflate",
            "BodyParameter", "BodyStream", "BodyUnbrotli", "BodyUncompressed",
            "Bytes", "Charset", "ClientIP", "ContentEncoding",
            "ContentType", "ContinueReadBody", "ContinueReadBodyStream", "Cookie",
            "CookieBytes", "Cookies", "DefaultPostForm", "DefaultQuery",
            "Form", "FormFile", "FormParams", "FormValue",
            "FullPath", "FullURI", "GetCookie", "GetFiles",
            "GetForm", "GetHeader", "GetHttpHeader", "GetMultipartForm",
            "GetPostForm", "GetPostFormArray", "GetPostFormMap", "GetQuery",
            "GetQueryArray", "GetQueryMap", "GetRawData", "GetRequestURI",
            "GetSecureCookie", "GetString", "GetStringMap", "GetStringMapString",
            "GetStringMapStringSlice", "GetStringSlice", "GetStrings", "GetSuperSecureCookie",
            "HeaderParameter", "Host", "LastPathSegment", "Locale",
            "MessageReceive", "MessageReceiveJSON", "MultipartForm", "MultipartFormBoundary",
            "MultipartReader", "MustBindWith", "ParamValues", "ParamsEscape",
            "ParseForm", "PathOriginal", "PathParameter", "PathParameters",
            "Peek", "PeekAll", "PeekBytes", "PeekKeys",
            "PeekMulti", "PeekMultiBytes", "PeekTrailerKeys", "PostBody",
            "PostForm", "PostFormArray", "PostFormMap", "PostFormValue",
            "QueryArray", "QueryEscape", "QueryMap", "QueryParam",
            "QueryParameter", "QueryParameters", "QueryParams", "QueryString",
            "QueryStrings", "RawHeaders", "ReadBody", "ReadEntity",
            "ReadFrame", "ReadHeader", "ReadJSON", "ReadLimitBody",
            "ReadMessage", "Reader", "Receive", "Refer",
            "Referer", "RequestBody", "RequestBodyStream", "RequestURI",
            "ShouldBind", "ShouldBindBodyWith", "ShouldBindHeader", "ShouldBindJSON",
            "ShouldBindQuery", "ShouldBindUri", "ShouldBindWith", "ShouldBindXML",
            "ShouldBindYAML", "String", "Trailer", "TrailerHeader",
            "URLParam", "URLParamFromCtx", "UserAgent", "UserData",
            "Vars",
        }),
        "sinks": frozenset({
            "Aggregate", "Alias", "AnalyticsQuery", "Attachment",
            "Chdir", "Chmod", "Chown", "Chtimes",
            "Column", "ColumnExpr", "Columns", "CombinedOutput",
            "Command", "CommandContext", "Compile", "CompileWithNS",
            "CountDocuments", "CreateProcess", "CreateProcessAsUser", "CreateTemp",
            "CrossJoin", "Delete", "DeleteMany", "DeleteOne",
            "DirFS", "Distinct", "DistinctOn", "DoCommit",
            "DoExec", "DoGetAll", "DoPrepare", "DoQuery",
            "Download", "EvalXPath", "EvalXPathAsBoolean", "Exec",
            "ExecContext", "ExecuteAnalyticsQuery", "ExecuteN1qlQuery", "Expr",
            "FileAttachment", "FilterRaw", "FindEach", "FindEachWithBreak",
            "FindOne", "FindOneAndDelete", "FindOneAndReplace", "FindOneAndUpdate",
            "ForkExec", "From", "GetAll", "GetArray",
            "GetCount", "GetDeadline", "GetOne", "GetScan",
            "GetStruct", "GetStructs", "GetTimeout", "Group",
            "GroupBy", "GroupExpr", "Having", "InnerJoin",
            "Insert", "InsertInto", "Into", "Join",
            "Joins", "Lchown", "LeftJoin", "Lstat",
            "MkdirAll", "MkdirTemp", "ModelTableExpr", "MustCompile",
            "MustExec", "MustParse", "NamedExec", "NamedQuery",
            "NewFile", "NewRaw", "NewRawQuery", "NotIn",
            "OpenFile", "Options", "Order", "OrderBy",
            "OrderExpr", "ParseExec", "ParseReader", "ParseString",
            "Pluck", "Prefix", "Prepare", "PrepareContext",
            "QueryAll", "QueryContext", "QueryOne", "QueryOneContext",
            "QueryOneParameterized", "QueryOneParameterizedContext", "QueryParameterized", "QueryParameterizedContext",
            "QueryRow", "QueryRowContext", "Queryx", "Queue",
            "QueueContext", "QueueOne", "QueueOneContext", "QueueOneParameterized",
            "QueueOneParameterizedContext", "QueueParameterized", "QueueParameterizedContext", "ReadDir",
            "ReadFile", "Readlink", "ReadlinkIfPossible", "Redirect",
            "RedirectBytes", "Remove", "RemoveAll", "Rename",
            "RenderFileName", "ReplaceOne", "RightJoin", "SaveFile",
            "SaveFileToStorage", "SaveFormFile", "SaveMultipartFile", "SaveToFile",
            "SaveToFileWithBuffer", "SaveUploadedFile", "Search", "SearchWithVariables",
            "Select", "SelectElement", "SelectElements", "SendFile",
            "SendFileBytes", "SendFileWithRate", "ServeFile", "ServeFileBytes",
            "ServeFileBytesUncompressed", "ServeFileUncompressed", "ServeFileWithRate", "SetExpr",
            "SetHost", "SetHostBytes", "SetRequestURI", "SetRequestURIBytes",
            "SetURI", "StartProcess", "Subquery", "Suffix",
            "SumInt", "Sums", "SumsInt", "Symlink",
            "Table", "TableExpr", "TempDir", "TempFile",
            "Truncate", "Update", "UpdateMany", "UpdateOne",
            "UploadFormFiles", "Watch", "Where", "WhereOr",
            "WriteContext", "WriteFile", "WriteOne", "WriteOneContext",
            "WriteOneParameterized", "WriteOneParameterizedContext", "WriteParameterized", "WriteParameterizedContext",
        }),
    },
    "java": {
        "sources": frozenset({
            "acceptInboundMessage", "afterConnectionClosed", "afterConnectionEstablished", "bindJSON",
            "bindJSONToList", "bindParameters", "bindParametersToList", "callDecode",
            "channelRead", "channelRead0", "configure", "cookie",
            "cookies", "decodeLast", "doCall", "getAcceptableLanguages",
            "getAcceptableMediaTypes", "getAttachmentAsByteArray", "getAttachmentAsDataHandler", "getAttributeBooleanValue",
            "getAttributeCount", "getAttributeFloatValue", "getAttributeIntValue", "getAttributeListValue",
            "getAttributeName", "getAttributeNameResource", "getAttributeNamespace", "getAttributeResourceValue",
            "getAttributeUnsignedIntValue", "getAttributeValue", "getBytes", "getClassAttribute",
            "getComment", "getContentBody", "getContentHeader", "getContentLength",
            "getContentType", "getCookies", "getCredentials", "getDescription",
            "getEntityStream", "getFieldName", "getFileItem", "getFileMap",
            "getFileNames", "getFiles", "getHeader", "getHeaderNames",
            "getHeaderString", "getHeaderValues", "getHeaders", "getIdAttribute",
            "getIdAttributeResourceValue", "getLanguage", "getLookupPathForRequest", "getMediaType",
            "getMultiFileMap", "getMultipartContentType", "getNamespace", "getOriginalFilename",
            "getOriginalRequestURI", "getOriginalUrl", "getOriginatingQueryString", "getOriginatingRequestUri",
            "getParameter", "getParameterMap", "getParameterNames", "getParameterValues",
            "getParams", "getPathInfo", "getPathWithinApplication", "getPathWithinServletMapping",
            "getPayload", "getPositionDescription", "getQuery", "getQueryParams",
            "getQueryString", "getRawUri", "getReader", "getRedirectUrl",
            "getReferer", "getRemoteUser", "getRequestCookieMap", "getRequestHeaderMap",
            "getRequestHeaderValuesMap", "getRequestParameterMap", "getRequestParameterNames", "getRequestParameterValuesMap",
            "getRequestPathInfo", "getRequestURI", "getRequestURIWithQueryString", "getRequestURL",
            "getRequestURLWithQueryString", "getRequestUri", "getResolvedLookupPath", "getRestOfPath",
            "getServletPath", "getString", "getStyleAttribute", "getSubmittedFileName",
            "getSubmittedForm", "getUri", "getUriInfo", "getUrl",
            "handle", "handleBinaryMessage", "handleCall", "handleCast",
            "handleDelivery", "handleMessage", "handlePongMessage", "handleStringCall",
            "handleTextMessage", "handleTransportError", "host", "isValid",
            "listDirectories", "listFiles", "listNames", "mapCall",
            "mlistDir", "nextDelivery", "onDataRead", "onHeadersRead",
            "onMessage", "onPushPromiseRead", "onText", "onUnknownFrame",
            "oneCookie", "postprocessReplyProperties", "preprocessReplyProperties", "primitiveCall",
            "queryString", "readFrame", "receive", "receiveBody",
            "receiveBodyNoWait", "receiveNoWait", "remoteAddress", "request",
            "resolveAndCacheLookupPath", "resolveSigningKey", "resolveSigningKeyBytes", "responseCall",
            "retrieveFile", "retrieveFileStream", "stringCall",
        }),
        "sinks": frozenset({
            "ANTLRFileStream", "AntClassLoader", "AtomicFileWriter", "BasicClassicHttpRequest",
            "BasicHttpEntityEnclosingRequest", "BasicHttpRequest", "BasicRequestProducer", "BatchSqlUpdate",
            "ChunkedFile", "ConfigurableHttpRequest", "DatagramPacket", "DefaultConstraintsRequest",
            "DefaultFullHttpRequest", "DefaultHttpRequest", "Delete", "DirectoryBrowserSupport",
            "DriverManagerDataSource", "FileBackedDataSource", "FileDataSource", "FileHandler",
            "FileImageOutputStream", "FileInputStream", "FileOutputStream", "FileOutputStreamFactory",
            "FileReader", "FileSystemResource", "FileUrlResource", "FileWriter",
            "FileWriterUtil", "FileWriterWithEncoding", "FullDuplexHttpStream", "GenericRecordJsonWriter",
            "GenericRecordXmlWriter", "HikariConfig", "HttpDelete", "HttpGet",
            "HttpHead", "HttpOptions", "HttpPatch", "HttpPost",
            "HttpPut", "HttpTrace", "HttpUriRequestBase", "JellyContext",
            "LargeText", "LockableFileWriter", "MappingSqlQuery", "MappingSqlQueryWithParameters",
            "MoveFileExA", "OldExcelExtractor", "OpenSslServerContext", "Options",
            "POIFSFileSystem", "Patch", "PathResource", "PrintStream",
            "PrintWriter", "ProcessBuilder", "RandomAccessFile", "RawSqlStatement",
            "ReopenableFileOutputStream", "Request", "RequestEntity", "RewindableFileOutputStream",
            "SeekableFileInput", "SimpleHttpRequest", "Socket", "SqlCall",
            "SqlFunction", "SqlQuery", "SqlUpdate", "StreamResult",
            "StreamTaskListener", "SyncableFileOutputStream", "Template", "Trace",
            "URIResolver", "URLClassLoader", "URLDataSource", "UpdatableSqlQuery",
            "UrlResource", "VBAMacroReader", "XmlFile", "XmlStreamReader",
            "XmlStreamWriter", "ZipFile", "ZipURLInstaller", "accept",
            "addArguments", "addBatch", "addBodyFileUpload", "addFileset",
            "addOneColumn", "addPathComponent", "addPicture", "analyticsQuery",
            "appendBytes", "appendText", "appendTo", "applyTemplates",
            "asByteSink", "asCharSink", "asCharSource", "asyncSearch",
            "authenticate", "baseUrl", "batchUpdate", "blobFileDescriptorForQuery",
            "browse", "bufferedWriter", "buildDir", "callFunction",
            "callMethod", "callTemplate", "canExecute", "canRead",
            "canWrite", "checkout", "cmdAsSingleString", "cmds",
            "command", "compareRemoteRevisionWith", "compile", "compileStatement",
            "connect", "console", "copyDirectory", "copyDirectoryToDirectory",
            "copyFile", "copyFileToDirectory", "copyFiles", "copyFrom",
            "copyInputStreamToFile", "copyRecursiveTo", "copyRecursively", "copyTo",
            "copyToByteArray", "copyToDirectory", "copyToFile", "copyToWithPermission",
            "copyURLToFile", "createClientKeyManager", "createDbFromSqlStatements", "createDirectories",
            "createDirectory", "createExtractor", "createFile", "createFileCodeWriter",
            "createLink", "createMutationQuery", "createNativeMutationQuery", "createNativeQuery",
            "createNewFile", "createOutputStream", "createPattern", "createPutObjectRequest",
            "createQuery", "createRelative", "createSQLQuery", "createSavepoint",
            "createSelectionQuery", "createStatement", "createSymbolicLink", "createTempDirectory",
            "createTempFile", "createTemplate", "createXPath", "createXPathFilter",
            "delete", "deleteDirectory", "deleteFile", "deleteIfExists",
            "deleteOnExit", "deleteQuietly", "deleteRecursively", "deserialize",
            "destination", "directory", "doExecute", "doLookup",
            "download", "dump", "errorWithMarkup", "evaluate",
            "evaluateExpression", "exec", "execPerConnectionSQL", "execSQL",
            "execute", "executeLargeUpdate", "executeQuery", "executeUpdate",
            "exists", "extract", "extractAll", "fastTail",
            "fetch", "filter", "filterList", "filterSet",
            "findByDn", "findOne", "findPattern", "findString",
            "findText", "findValue", "flatMap", "forServer",
            "forceDelete", "forceDeleteOnExit", "forceMkdir", "forceMkdirParent",
            "fromFile", "fromJSON", "fromXML", "getChild",
            "getColumns", "getConnection", "getFieldValue", "getFileStore",
            "getFileSystem", "getFileToWrite", "getForObject", "getFormatted",
            "getLiteralTemplate", "getPrimaryKeys", "getRandomAccess", "getResourceAsStream",
            "getResources", "getSession", "getSystemResource", "getSystemResourceAsStream",
            "getSystemResources", "getTemplate", "getURLClassLoader", "getValueList",
            "getValueNode", "getValueString", "getValueUsingOgnl", "getWriter",
            "hasKey", "headForHeaders", "inputStream", "insert",
            "install", "installIfNecessaryFrom", "isDirectory", "isExist",
            "isFile", "isHidden", "isTrue", "jsonToJava",
            "launch", "launchChannel", "lines", "listBindings",
            "literalHtml", "loadCatalog", "loadData", "loadDataWithBaseURL",
            "loadFile", "loadJSON", "loadJSONHTML", "loadStream",
            "loadStreamOfType", "loadType", "longForQuery", "lookup",
            "lookupContext", "lookupLink", "makeSelectList", "mapProperties",
            "mapValue", "matches", "mergeTemplate", "method",
            "mkdirs", "moveDirectory", "moveDirectoryToDirectory", "moveFile",
            "moveFileToDirectory", "moveToDirectory", "newBufferedReader", "newBufferedWriter",
            "newBuilder", "newCall", "newFileSystem", "newHttpRequest",
            "newInputStream", "newInputStreamDenyingSymlinkAsNeeded", "newOutputStream", "newRequest",
            "newWebSocket", "newWriter", "notExists", "numberValueOf",
            "okWithMarkup", "openConnection", "openInputStream", "openOutputStream",
            "openReader", "options", "optionsForAllow", "outputStream",
            "parseClass", "parseSingle", "patch", "patchForObject",
            "postForLocation", "postForObject", "prepareCall", "prepareStatement",
            "printWriter", "probeContentType", "process", "processThrottled",
            "putStringResource", "putTemplate", "queryForList", "queryForMap",
            "queryForObject", "queryForRowSet", "queryForStream", "queryNumEntries",
            "queryStreaming", "queryWithFactory", "rawQuery", "rawQueryWithFactory",
            "readAllBytes", "readAllLines", "readBytes", "readData",
            "readFileToByteArray", "readFromOffset", "readLines", "readObject",
            "readString", "readText", "readToString", "readTrim",
            "readValue", "redirectError", "redirectOutput", "redirectTo",
            "releaseSavepoint", "removeDir", "rename", "renameOrMoveFilesInParallel",
            "renameTo", "render", "renderForResult", "resolve",
            "resourceToString", "respond", "result", "returnGeneratedValues",
            "reverseProxyTo", "rewriteHudsonWar", "rollbackTransactionToSavepoint", "runCommand",
            "search", "searchForContext", "searchForEntry", "searchForObject",
            "seeOther", "selectAll", "selectNodes", "selectObject",
            "selectOne", "selectSingleNode", "sendRedirect", "sendRedirect2",
            "serializeToFile", "serveFile", "serveLocalizedFile", "setAddress",
            "setBasedir", "setDest", "setEntity", "setExecutable",
            "setFile", "setHttpHost", "setJdbcUrl", "setLastModified",
            "setParameter", "setProperties", "setProperty", "setReadOnly",
            "setReadable", "setResource", "setSocketAddress", "setSql",
            "setSrc", "setTodir", "setTofile", "setURI",
            "setUri", "setUrl", "setValue", "setWritable",
            "sort", "source", "staticResource", "stringForQuery",
            "target", "temporaryRedirect", "then", "toByteArray",
            "trace", "transform", "translateVariables", "translateVariablesCollection",
            "trustManager", "tryFindValue", "tryFindValueWhenExpressionIsNotNull", "trySetValue",
            "unmarshal", "unzipFrom", "update", "updateEntity",
            "updateIntegrityHMAC", "updatePartitionColumnStatistics", "updateWithOnConflict", "valueOf",
            "viewFile", "viewFileOld", "warningWithMarkup", "writeByteArrayToFile",
            "writeBytes", "writeLines", "writeString", "writeStringToFile",
            "writeText", "writeTo", "writeValue", "writer",
        }),
    },
    "javascript": {
        "sources": frozenset({
            "ApolloServer,ApolloServerBase", "resolve",
        }),
        "sinks": frozenset({
            "Expression", "QueryString", "Statement", "createProcStatement",
            "exec,prepare", "exec,prepare,execute", "loadProcedure", "makeDirectory,makeDirectorySync",
            "nativeSync,native,manual,manualSync,mkdirpNative,mkdirpManual,mkdirpManualSync,mkdirpNativeSync,mkdirpSync,sync", "openApp", "rimrafSync,nativeSync,manualSync,windowsSync,moveRemoveSync,posixSync", "sync",
            "sync,native,manual,windows,moveRemove,posix",
        }),
    },
    "tsx": {
        "sources": frozenset({
            "ApolloServer,ApolloServerBase", "resolve",
        }),
        "sinks": frozenset({
            "Expression", "QueryString", "Statement", "createProcStatement",
            "exec,prepare", "exec,prepare,execute", "loadProcedure", "makeDirectory,makeDirectorySync",
            "nativeSync,native,manual,manualSync,mkdirpNative,mkdirpManual,mkdirpManualSync,mkdirpNativeSync,mkdirpSync,sync", "openApp", "rimrafSync,nativeSync,manualSync,windowsSync,moveRemoveSync,posixSync", "sync",
            "sync,native,manual,windows,moveRemove,posix",
        }),
    },
    "typescript": {
        "sources": frozenset({
            "ApolloServer,ApolloServerBase", "resolve",
        }),
        "sinks": frozenset({
            "Expression", "QueryString", "Statement", "createProcStatement",
            "exec,prepare", "exec,prepare,execute", "loadProcedure", "makeDirectory,makeDirectorySync",
            "nativeSync,native,manual,manualSync,mkdirpNative,mkdirpManual,mkdirpManualSync,mkdirpNativeSync,mkdirpSync,sync", "openApp", "rimrafSync,nativeSync,manualSync,windowsSync,moveRemoveSync,posixSync", "sync",
            "sync,native,manual,windows,moveRemove,posix",
        }),
    },
}
